#!/bin/bash
#
# Kirjutatakse üks täisarv ja arvutatakse jäägi summa
#
echo "kirjuta üks täisarv"

read -a arv
arv1=$arv
summa=0
while [ $arv -ne 0 ]
do
	jaak=$(($arv % 10))
	summa=$(($summa + $jaak))
	arv=$(($arv / 10))
done
echo "Taisarvu $arv1 numbrite summa on $summa"
# Skripti lõpp
