#!/bin/bash
#
# Skript- Sisestades numbri 1-12 saad vastuseks kuu jaanuarist - detsembrini 
#

echo "Sisesta number ja saad vastava kuu:"
read kuu

if [[ $kuu -le 12 ]] 
then 
case $kuu in
	"1") echo "Jaanuar";;
	"2") echo "Veebruar";;
	"3") echo "Märts";;
	"4") echo "Aprill";;
	"5") echo "Mai";;
	"6") echo "Juuni";;
	"7") echo "Juuli";;
	"8") echo "August";;
	"9") echo "September";;
	"10") echo "Oktoober";;
	"11") echo "November";;
	"12") echo "detsember";;
esac
else
	echo "Sellise numbriga kuud ei ole"
fi
#lõpp
