#!/bin/bash
# See skript annab tänase kuupäeva ja kellaaja koos kalendrikuuga.
echo -n "Today is "
date +"%A %B %Y"
echo -n "Time is " 
date +"%H:%M"
echo

echo -n "Calender of " 
date +"%B %Y" 
cal | tail -n 7

# Skripti lõpp
